### PR TITLE
Tailwind version

### PR DESCRIPTION
**Pull request by mingness**
Format website to figma design using tailwind css.

---
branch will be deployed to http://prachtsaal-berlin-tailwind-version.surge.sh

### CODE REVIEW

**Comment by mingness** [comment]
to fix:
* on phone, burger menu items could be aligned better
* on phone, space out logo and burger menu icon
* on phone, a little more spacing between contact us and address
* on phone, center social icons, address
* on phone, center upcoming events
* on phone, more spacing between events; put date right justified?
* event portfolio bottom margin
* about us doesn't fit on phone

**Comment by mingness** [comment]
@hamoid what was your goal for the last commit? Not sure if the whole outcome was your purpose :)

**Comment by mingness** [comment]
Current state is a good minimal website. Plan to deploy in the next days, after a few more eyes on it.

**Review by hamoid — APPROVED** [review]
I think we've been testing this daily for weeks, so it should be fine. Any issues can be fixed after merging.

**Pull request merged**
